<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>health</artifactId>
        <groupId>com.health</groupId>
        <version>3.9.2</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>health-report</artifactId>

    <description>
        综合健康报告模块
    </description>

    <dependencies>

        <!-- 通用工具-->
        <dependency>
            <groupId>com.health</groupId>
            <artifactId>health-common</artifactId>
        </dependency>

        <!-- AI 模块 -->
        <dependency>
            <groupId>com.health</groupId>
            <artifactId>health-ai</artifactId>
            <version>${health.version}</version>
        </dependency>

    </dependencies>

</project>
